---
- name: Include OS variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family is defined

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: user.yml
